version: '2.0'
services:
  mysql_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'todo_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
